### ISSUE TITLE
Yaml worker can't read properties of undefined

### ISSUE THREAD

**Issue by no1melman** [remcohaszing/monaco-yaml#238] opened 2024-06-19 15:33 UTC
```
TypeError: Cannot read properties of undefined (reading 'indexOf')
    at resolveRefs (http://localhost:5173/node_modules/.vite/deps/monaco-yaml_yaml__worker__js.js?v=8e002f8b:29936:27)
    at YAMLSchemaService.resolveSchemaContent (http://localhost:5173/node_modules/.vite/deps/monaco-yaml_yaml__worker__js.js?v=8e002f8b:29962:11)
    at http://localhost:5173/node_modules/.vite/deps/monaco-yaml_yaml__worker__js.js?v=8e002f8b:26721:32
    at async YamlCompletion.doComplete (http://localhost:5173/node_modules/.vite/deps/monaco-yaml_yaml__worker__js.js?v=8e002f8b:31640:23)
```

![image](https://github.com/remcohaszing/monaco-yaml/assets/13630254/f044ffcc-6a8e-44e1-9dd2-688d0a3b3384)

I'm not sure where this has come from. I've followed your vite example.

**Comment by remcohaszing** [comment] 2024-06-20 11:41
Please provide and example repository and exact steps to reproduce.

**Comment by Lichenhao01** [comment] 2024-07-10 09:38
Hello, do you have a demo that combines monaco-editor with monaco-yaml? It's a relatively simple demo. I'm a beginner

**Comment by remcohaszing** [comment] 2024-07-11 12:33
@Lichenhao01 That’s not related to this issue. Anyway, see https://github.com/remcohaszing/monaco-yaml#examples

**Comment by remcohaszing** [comment] 2024-08-18 09:38
I’m closing this because there’s no reproduction.

**Closed by remcohaszing** 2024-08-18 09:38 UTC
