### ISSUE TITLE
The error message for the enumeration type is incorrect

### ISSUE THREAD

**Issue by MrWindlike** [remcohaszing/monaco-yaml#236] opened 2024-06-04 06:18 UTC
### Problem

When a field with multiple enum types is filled in incorrectly, the prompt shows a collection of enum results for multiple fields.

Schema:
```json
        {
          "properties": {
            "p": {
              "type": "string",
              "enum": ["a", "b"],
            },
            "q": {
              "type": "string",
              "enum": ["c", "d"]
            }
          }
        }
```

Result:

<img width="549" alt="image" src="https://github.com/remcohaszing/monaco-yaml/assets/25414733/0494ed51-a451-4284-8c06-e75848a72848">

### Expectation

Only the enumeration results for the corresponding field are displayed.

**Comment by remcohaszing** [comment] 2024-08-18 09:38
I’m closing this because there’s no reproduction and this is likely an upstream issue.

**Closed by remcohaszing** 2024-08-18 09:38 UTC
